apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: prod
commonLabels:
  environment: prod
patchesStrategicMerge:
- patches/deployment.yaml
- patches/configmap.yaml
