apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: dev
commonLabels:
  environment: dev
patchesStrategicMerge:
- patches/deployment.yaml
- patches/configmap.yaml
